export default {
    pages: [
        {
            id: 16,
            title: "First Start Page",
            content: "I am make many story. Thus it shall be.",
            isStart: true,
            isTBC: false,
            isEnding: false,
            isLinked: false,
            isOrphaned: false,
            contentFinished: false,
            createdAt: "2022-03-01 03:58:17",
            updatedAt: "2022-03-03 03:58:17",
            AuthorId: 3,
            StoryId: 1
        },
        {
            id: 18,
            title: "Page 2",
            content: "I am make many story. Thus it shall be.",
            isStart: false,
            isTBC: true,
            isEnding: false,
            isLinked: true,
            isOrphaned: false,
            contentFinished: true,
            createdAt: "2022-03-01 03:58:17",
            updatedAt: "2022-03-01 03:58:17",
            AuthorId: 3,
            StoryId: 1
        },
        {
            id: 19,
            title: "A page with a medium length title for visuals.",
            content: "I am make many story. Thus it shall be.",
            isStart: false,
            isTBC: false,
            isEnding: true,
            isLinked: true,
            isOrphaned: false,
            contentFinished: false,
            createdAt: "2022-03-01 03:58:17",
            updatedAt: "2022-03-21 03:58:17",
            AuthorId: 3,
            StoryId: 1
        },
        {
            id: 25,
            title: "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musi",
            content: "I am make many story. Thus it shall be.",
            isStart: false,
            isTBC: false,
            isEnding: false,
            isLinked: false,
            isOrphaned: true,
            contentFinished: false,
            createdAt: "2022-03-01 03:58:17",
            updatedAt: "2022-03-05 03:58:17",
            AuthorId: 3,
            StoryId: 1
        },
        {
            id: 10,
            title: "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musi",
            content: "I am make many story. Thus it shall be.",
            isStart: false,
            isTBC: false,
            isEnding: false,
            isLinked: false,
            isOrphaned: true,
            contentFinished: true,
            createdAt: "2022-03-01 03:58:17",
            updatedAt: "2022-03-05 03:58:17",
            AuthorId: 3,
            StoryId: 1
        },
        {
            id: 10,
            title: "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musi",
            content: "I am make many story. Thus it shall be.",
            isStart: false,
            isTBC: false,
            isEnding: false,
            isLinked: true,
            isOrphaned: false,
            contentFinished: true,
            createdAt: "2022-03-01 03:58:17",
            updatedAt: "2022-03-05 03:58:17",
            AuthorId: 3,
            StoryId: 1
        }
    ],
    stories: [
        {
            id: 2,
            title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean m",
            description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel t",
            isPublic: true,
            isFinished: true,
            doneByDefault: false,
            chooseNotToWarn: false,
            violence: false,
            nsfw: false,
            nonConsent: false,
            characterDeath: false,
            profanity: false,
            createdAt: "2022-02-28 20:12:07",
            updatedAt: "2022-02-28 20:12:07",
            AuthorId: 3
        },
        {
            id: 3,
            title: "Jack and Jill",
            description: "Went up the hill... and then what?",
            isPublic: true,
            isFinished: true,
            doneByDefault: false,
            chooseNotToWarn: false,
            violence: false,
            nsfw: false,
            nonConsent: false,
            characterDeath: false,
            profanity: false,
            createdAt: "2022-02-28 20:12:07",
            updatedAt: "2022-03-28 20:12:07",
            AuthorId: 3
        },
        {
            id: 4,
            title: "Rapunzel",
            description: "Will you go up the tower?",
            isPublic: true,
            isFinished: true,
            doneByDefault: false,
            chooseNotToWarn: false,
            violence: false,
            nsfw: false,
            nonConsent: false,
            characterDeath: false,
            profanity: false,
            createdAt: "2022-02-28 20:12:07",
            updatedAt: "2022-03-21 20:12:07",
            AuthorId: 3
        }
    ],
}